### ISSUE TITLE
What raise 'NoneType' object is not callable?

### ISSUE THREAD

**Issue by KazusaW1999** [symphonynet/SymphonyNet#13]
2022-10-13 21:17:34 | INFO | fairseq_cli.train | task: symphony_modeling (SymphonyModelingTask)
2022-10-13 21:17:34 | INFO | fairseq_cli.train | model: linear_transformer_multi (LinearTransformerMultiHeadLM)
2022-10-13 21:17:34 | INFO | fairseq_cli.train | criterion: multiple_loss (MultiplelossCriterion)
2022-10-13 21:17:34 | INFO | fairseq_cli.train | num. model params: 39127552 (num. trained: 39127552)
2022-10-13 21:17:39 | INFO | fairseq.trainer | detected shared parameter: decoder.proj_evt.bias <- decoder.proj_dur.bias
2022-10-13 21:17:39 | INFO | fairseq.trainer | detected shared parameter: decoder.proj_evt.bias <- decoder.proj_trk.bias
2022-10-13 21:17:39 | INFO | fairseq.trainer | detected shared parameter: decoder.proj_evt.bias <- decoder.proj_ins.bias
2022-10-13 21:17:39 | INFO | fairseq.utils | ***********************CUDA enviroments for all 1 workers***********************
2022-10-13 21:17:39 | INFO | fairseq.utils | rank   0: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-SXM2-32GB                    
2022-10-13 21:17:39 | INFO | fairseq.utils | ***********************CUDA enviroments for all 1 workers***********************
2022-10-13 21:17:39 | INFO | fairseq_cli.train | training on 1 devices (GPUs/TPUs)
2022-10-13 21:17:39 | INFO | fairseq_cli.train | max tokens per GPU = None and max sentences per GPU = 2
2022-10-13 21:17:39 | INFO | fairseq.trainer | no existing checkpoint found ckpt/checkpoint_last_linear_4096_chord_bpe_hardloss1_PI2.pt
2022-10-13 21:17:39 | INFO | fairseq.trainer | loading train data for epoch 1
2022-10-13 21:17:39 | INFO | fairseq.data.data_utils | loaded 5243 examples from: data/model_spec/linear_4096_chord_bpe_hardloss1/bin/train
2022-10-13 21:17:39 | INFO | fairseq.trainer | NOTE: your device may support faster training with --fp16
2022-10-13 21:17:39 | INFO | fairseq.trainer | begin training epoch 1
Traceback (most recent call last):
  File "/data/home/scv5187/.conda/envs/design/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fairseq_cli/train.py", line 125, in main
    valid_losses, should_stop = train(args, trainer, task, epoch_itr)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fairseq_cli/train.py", line 208, in train
    log_output = trainer.train_step(samples)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fairseq/trainer.py", line 486, in train_step
    ignore_grad=is_dummy_batch,
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fairseq/tasks/fairseq_task.py", line 416, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/scv5187/SymphonyNet/src/fairseq/linear_transformer/linear_transformer_multi.py", line 55, in forward
    net_output = model(**sample["net_input"])
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fairseq/models/fairseq_model.py", line 481, in forward
    return self.decoder(src_tokens, **kwargs)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/scv5187/SymphonyNet/src/fairseq/linear_transformer/linear_transformer_multi.py", line 281, in forward
    features = self.extract_features(x, src_lengths)
  File "/data/home/scv5187/SymphonyNet/src/fairseq/linear_transformer/linear_transformer_multi.py", line 341, in extract_features
    outputs = self.model(x, self.attn_mask, len_mask)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fast_transformers/transformers.py", line 138, in forward
    x = layer(x, attn_mask=attn_mask, length_mask=length_mask)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fast_transformers/transformers.py", line 81, in forward
    key_lengths=length_mask
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fast_transformers/attention/attention_layer.py", line 109, in forward
    key_lengths
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fast_transformers/attention/causal_linear_attention.py", line 101, in forward
    values
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fast_transformers/attention/causal_linear_attention.py", line 23, in causal_linear
    V_new = causal_dot_product(Q, K, V)
  File "/data/home/scv5187/.conda/envs/design/lib/python3.6/site-packages/fast_transformers/causal_product/__init__.py", line 48, in forward
    product
TypeError: 'NoneType' object is not callable

**Comment by hhhyc333** [comment]
I meet the same issue，why？
